# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eK9lowUM1XthxY1fC9tCLv-XgJICcDWN
"""

!pip install streamlit
import streamlit as st
import hashlib
from datetime import datetime

# Initialize session state for the hospital ledger if not already present
if "hospital_ledger_advanced" not in st.session_state:
    st.session_state.hospital_ledger_advanced = {}

# Function to generate a hash for a visit record
def generate_hash(patient_name, treatment, cost, date_of_visit):
    visit_data = patient_name + treatment + str(cost) + date_of_visit
    visit_hash = hashlib.sha256(visit_data.encode()).hexdigest()
    return visit_hash

# App title
st.title("🏥 Advanced Hospital Ledger with Hashing")

# Form for patient visit
with st.form("add_visit_form"):
    st.subheader("Add a Patient Visit")

    patient_name = st.text_input("Patient Name")
    treatment = st.text_input("Treatment Received")
    cost = st.number_input("Treatment Cost ($)", min_value=0.0, format="%.2f")
    date_of_visit = st.date_input("Date of Visit", value=datetime.today())

    submitted = st.form_submit_button("Add Visit")

    if submitted and patient_name and treatment and cost and date_of_visit:
        date_str = date_of_visit.strftime("%Y-%m-%d")
        visit_hash = generate_hash(patient_name, treatment, cost, date_str)

        visit = {
            "patient_name": patient_name,
            "treatment": treatment,
            "cost": cost,
            "date_of_visit": date_str,
            "visit_hash": visit_hash
        }

        if patient_name not in st.session_state.hospital_ledger_advanced:
            st.session_state.hospital_ledger_advanced[patient_name] = []

        st.session_state.hospital_ledger_advanced[patient_name].append(visit)

        st.success(f"Visit added for {patient_name} on {date_str}.")
        st.code(visit_hash, language="text")

# Display the ledger
if st.session_state.hospital_ledger_advanced:
    st.subheader("📋 Advanced Hospital Ledger")
    for patient, visits in st.session_state.hospital_ledger_advanced.items():
        st.markdown(f"### 👤 {patient}")
        for visit in visits:
            st.write(f"- **Treatment:** {visit['treatment']}")
            st.write(f"  - Cost: ${visit['cost']}")
            st.write(f"  - Date: {visit['date_of_visit']}")
            st.code(f"Hash: {visit['visit_hash']}")
else:
    st.info("No patient visits recorded yet.")